### ISSUE TITLE
[Bug] wrong interpretation of path attribute specified in configure() function

### ISSUE THREAD

**Issue by peppetort** [mett96/loggerpy#1]
Calling `configure()` specifying the log file creation path, the program automatically creates all the folders specified in the path,  starting from the program folder instead of the `/` directory.
For example: if the folder of my program is `/home/peppetort/Desktop/my_python_program/` and the absolute path to the specified log file is `/home/peppetort/my_python_program/log_dir/`, it will be created in `/home/peppetort/my_python_program/home/peppetort/my_python_program/log_dir/logs/today_date.log` (logs is created by default)

**Comment by sank96** [comment]
This bug has been fixed in 
fixed #2 
merge request.

I close this issue. Thanks for the report
